name: Build

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pandoc/actions/setup@v1
        with:
          version: 3.2.1
      - uses: astral-sh/setup-uv@v5
        with:
          version: 0.5.18
      - name: Build
        run: make build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist/
